### ISSUE TITLE
v0.1.0

### ISSUE THREAD

**Issue by Tjatse** [Tjatse/pm2-gui#1]
- [x] Multiple operations.
- [x] ~~Configured JSON files.~~
- [x] Memory and CPU usage gauge of each process.
- [x] More test cases.
- [x] ANSI monitor (curses-like dashboard)

**Comment by twayz** [comment]
nice job with this project!  would you also be able to add the ability to do a "pm2 pull app" for the running node? also would you be able to allow the pm2-gui process to start in the background without any output in the terminal just like how pm2 works when starting an app?
thanks!!

**Comment by Tjatse** [comment]
@twayz Thanks for the feedback, I'm going to support the features you talk about, but currently spending too much time on my job and maintaining PM2, so it will be proceeded slowly. :D
