### ISSUE TITLE
    throw new Error('Can not load PM2 config, the file "' + pm2ConfPath + '" d

### ISSUE THREAD

**Issue by 0x4139** [Tjatse/pm2-gui#10]
Even if the file exists in .pm2/conf.js

**Comment by Aure77** [comment]
same problem

**Comment by Tjatse** [comment]
Node ver?
Platform?

**Comment by Aure77** [comment]
I solve the problem by copying https://github.com/Tjatse/pm2-gui/blob/master/test/fixtures/conf.js into ~/.pm2/conf.js
By default pm2 use an empty `conf.js` file

**Comment by 0x4139** [comment]
do you want a pull request @Tjatse with the fix?

**Comment by Tjatse** [comment]
@0x4139 
I've been very busy recently, it's Chinese New Year...   :)
It will be appreciated if you can send a PR to fix this.

**Comment by Tjatse** [comment]
It should be fixed @v0.0.9.

**Comment by kevincaradant** [comment]
Hi

I think this issue is linked with my issue: https://github.com/Tjatse/pm2-gui/issues/47

Is it posible someone provides me a example of conf.js ? 

Thank you
