### ISSUE TITLE
No.Debug

### ISSUE THREAD

**Issue by MeisterRoerich** [Tjatse/pm2-gui#11]
How can I use pm2-gui with no outputs on the server console?
I cant do anything after starting pm2 gui
Its a great tool

**Comment by Tjatse** [comment]
try
```bash
$ pm2-gui start --no-debug
```

**Comment by MeisterRoerich** [comment]
![bildschirmfoto vom 2015-02-15 11 18 55](https://cloud.githubusercontent.com/assets/3585860/6202897/823fb390-b504-11e4-85dd-8ea7b94122a1.png)
I cant do anything after i entered the command

**Comment by Tjatse** [comment]
@MeisterRoerich 
[daemonic](https://github.com/Tjatse/pm2-gui/tree/next#run-web-interface) is what you want:
```bash
# start
$ nohup pm2-gui start > /dev/null 2>&1 & echo $! > /path/to/pm2-gui.pid
# stop
$ kill -9 `cat /path/to/pm2-gui.pid`
```

**Comment by MeisterRoerich** [comment]
Thank you very much
