### ISSUE TITLE
doesn't run when server is run behind a Proxypass in apache

### ISSUE THREAD

**Issue by shaunakv1** [Tjatse/pm2-gui#12]
I am running the server behind a proxy pass, so something like foo.com/pm2-gui  goes to localhost:8088

Problem is, UI html includes all assets relative to domain so it is trying to include assets like:

http://foo.com/css/bootstrap.min.css which obviously fails. Can you change the assets to be included using a full relative path? 

For example, you include assets like 

`<script type="text/javascript" src="/js/bootstrap.min.js"></script>`

instead they should be included as 

`<script type="text/javascript" src="js/bootstrap.min.js"></script>`

and same goes with the CSS..

thanks! 
Shaunak

**Comment by Tjatse** [comment]
Yup. thanks.

**Comment by shaunakv1** [comment]
This problem runs deeper. the socket communication also needs to be fixed. To fix this, I think there will have to be a configuration prefixed in the .conf file where users can set their server paths..

**Comment by Tjatse** [comment]
Just checkout the `next` branch and do what you wanna do.
Appreciate!!!

**Comment by Tjatse** [comment]
It should be fixed @v0.0.9.
