### ISSUE TITLE
"startup" command as pm2 for service ?

### ISSUE THREAD

**Issue by thco** [Tjatse/pm2-gui#14]
Hi.

There is a plan to build a startup command as pm2 does to create /init.d service script for an auto boot start ?

Thanks

**Comment by Tjatse** [comment]
Take a look at [this](https://github.com/Tjatse/pm2-gui/tree/next#run-web-interface).
```bash
# start
$ nohup pm2-gui start > /dev/null 2>&1 & echo $! > /path/to/pm2-gui.pid
# stop
$ kill -9 `cat /path/to/pm2-gui.pid`
```

**Comment by thco** [comment]
Okay, my bad. I'm sorry, did not notice that.

Thanks ! I'll try to make an init.d script with that

**Comment by Tjatse** [comment]
That's very kind of you ^.^
I am working on `next` branch and there are lots breaking changes and new features.
