### ISSUE TITLE
How to manage remote process?

### ISSUE THREAD

**Issue by dbuarque** [Tjatse/pm2-gui#19]
Hey @Tjatse,

How can I manage a remote process?

**Comment by Tjatse** [comment]
Since PM2@0.11.*, you can not do that, because of security issues.
You can deploy pm2-gui@latest on your remote server, and run `pm2-gui start`, enable the web port (8088 as defualt) in **iptables**(/etc/sysconfig/iptables):
```iptables
-A INPUT -m state --state NEW -m tcp -p tcp --dport 8088 -j ACCEPT
```

After:
```bash
service iptables restart
```

Visit:
```
http://[remote address]:8088/
```

**Comment by Tjatse** [comment]
Supported @0.1.2!

**Comment by SukantGujar** [comment]
Hi, is this supported now?

**Comment by nitrocode** [comment]
@Tjatse great job with this app. The gui looks well refined and perfect for our app.

I see it's possible to remotely monitor multiple hosts by defining the hosts within the sample config

```
; pm2@171 = AuTh@https://192.168.1.171:9002/sockserv
; pm2@172 = 192.168.1.172:9001
; pm2@173 = 192.168.1.173:9000
```

but do I need to setup pm2-gui on each host that runs my app? how do I set this up? Do I just install it, change the password in the ini file, and run your app on each host alongside my app with the port exposed?

I also noticed you changed the port each time in the sample. Any significance of that?

Thank you.

**Comment by Tjatse** [comment]
@nitrocode 
1. just run `pm2-gui agent /path/to/pm2-gui.ini` on your servers and make sure the port you're using is not being blocked by firewalls(iptables...)
2. host `pm2-gui start /path/to/pm2-gui.ini` on the web server, and make sure all the agents can be resolved
3. visit the `http://[your web server address/ip]`
4. changing the port only for testing....:)

**Comment by nitrocode** [comment]
Ah ok that sounds doable. Different issue but I wonder if we can continue to expose port 80 externally and expose the pm2-gui port internally so we can monitor on-prem and reduce the attack surface.

Thanks!
