### ISSUE TITLE
v0.2.0

### ISSUE THREAD

**Issue by Tjatse** [Tjatse/pm2-gui#20]
- [ ] Unstable restart alert (Mail or SMS, hook it).
- [x] Remote monitor & control (`mon` and `web`).
- [ ] Real-time memory and CPU usage.
- [ ] Send signal to a specific process.
- [ ] Blabla

**Comment by wanglong167** [comment]
Very expecting

**Comment by wanglong167** [comment]
add Multi-Server Management

**Comment by wanglong167** [comment]
哥们什么时候加上  多服务器 建议吧前后台分开 这样就可以通过ip 添加server了

**Comment by wanglong167** [comment]
Cannot find module '/usr/bin/lib/daemon'

**Comment by wanglong167** [comment]
Cannot find module '/usr/bin/lib/daemon'

**Comment by c0rrre** [comment]
add multi user please

**Comment by ageorgios** [comment]
awesome work

please include:

- wider terminal to show logs
- ability to git pull and restart
