### ISSUE TITLE
RAM/Memory usage is wrong

### ISSUE THREAD

**Issue by deathlord87** [Tjatse/pm2-gui#22]
Monitoring through ```htop``` provides more free ram while pm2-gui says 100 when there's still 50% free ram available.

Also ```free -m``` provides the correct info, how is the pm2-gui calculating the Free RAM/Memory ?

I believe the right calculation of RAM = total mem - (physical free mem + cache mem)

The below info turned out to be 100% full as per pm2-gui but there's a lot of free mem available.

total       used       free     shared    buffers     cached
Mem:        128833     128229        603          3        173      76197
-/+ buffers/cache:      51857      76975
Swap:       130975        163     130812

**Comment by Tjatse** [comment]
Really? I'm using `os` module to calculate memory usage. e.g.:
```javascript
get memory(){
  return {
    free      : os.freemem(),
    total     : os.totalmem(),
    percentage: Math.round(100 * (1 - os.freemem() / os.totalmem()))
  }
}
```

I'll test on my servers to investigate this issue.

**Comment by deathlord87** [comment]
os.freememory() & os.totalmem()
Returns the amount of free system memory in bytes which needs to be factored into while doing the math

Seems like there may be errors with the os.freemem() itself, htop returns a more accurate usage of memory than the node os module. 

Need verification though :+1:

**Comment by MCOfficer** [comment]
might be necroposting, but i'm having the exact same issue.

could it be due to the server being a vps?

**Comment by Tjatse** [comment]
might be, `free` or `cpuinfo` can not describe the correct information of container/vps sometimes.

**Comment by MCOfficer** [comment]
would make sense. i'll see if i can find some workaround.
