### ISSUE TITLE
Does pm2-gui support for multi-server ?

### ISSUE THREAD

**Issue by mike442144** [Tjatse/pm2-gui#24]
I have 10 workers running pm2. Can I monitor in web together?

**Comment by Tjatse** [comment]
Sorry, you can't!
But I'm just working on a production one for monitoring PM2 servers (free), and this will not be a problem.
```
agent \

agent  --  Server -- Web 

agent /
```

It bases on InfluxDB (time series metrics, events and analytics), could do all the jobs that `pm2-gui` does and including:
- Timeline of events
- Status of triggers (`restart` / `stop` warning - SMS / Email)
- I/O frequence
- Network latency 
- ...

**Comment by mike442144** [comment]
@Tjatse That's cool, I couldn't even find a project that could monitor multi-servers, do you know any project?
What's your new production code link? Can I have look and commit code if possible?

**Comment by Tjatse** [comment]
Appreciate for your passion, it's still in constructing and developing, I'll publish it ASAP!

**Comment by mike442144** [comment]
Thank you. Looking forward this cool project.
