### ISSUE TITLE
Rather than a pop up, consider a HUD of all the Processes for Monitoring 

### ISSUE THREAD

**Issue by chrisamoore** [Tjatse/pm2-gui#25]
- maybe http://masonry.desandro.com/ like grid for the amount of processes ?

**Comment by Tjatse** [comment]
Thanks a lot @chrisamoore 
At the beginning, I created this rep for monitoring my PM2 processes during the PM2 dev, as we all known it's not easy to monitor remoting processes by PM2 CLI, and I certainly not anticipated that so many people are interesting about this project, they sent Emails and Notifications to provide helps and suggestions (just like you ;) ), I really appreciate that.

I'm currently working on a productive & professional one, it bases on InfluxDB (time series metrics, events and analytics), could do all the jobs that `pm2-gui` does and including:
- Timeline of PM2 events
- Status of triggers (restart / stop warning - SMS / Email)
- I/O frequency
- Network latency (response time, Apdex stuffs)

And I'll consider your suggestion, it's really pretty cool. 

Powered by bouncy's dashboard UI:
![03_dark_vr_dashboard](https://cloud.githubusercontent.com/assets/1418444/8889312/2bf03998-3307-11e5-9a47-4b2834f92a72.jpg)
