### ISSUE TITLE
fails to run when installed globally

### ISSUE THREAD

**Issue by boneskull** [Tjatse/pm2-gui#30]
```
$ pm2-gui start
/usr/bin
[INFO] Starting...
module.js:328
    throw err;
    ^

Error: Cannot find module '/usr/bin/lib/daemon'
    at Function.Module._resolveFilename (module.js:326:15)
    at Function.Module._load (module.js:277:25)
    at Function.Module.runMain (module.js:442:10)
    at startup (node.js:136:18)
    at node.js:966:3
[WARN] ✘ stopped
```

This is because the following line in `pm2-gui` is incorrect:

```
SRC=$(cd $(dirname "$0"); pwd)
```

It's [difficult](http://stackoverflow.com/questions/3572030/bash-script-absolute-path-with-osx) to implement a cross-platform solution with shell scripts, due to a lack of `realpath` on MacOS X, and a different implementation of `readlink`.  

The best suggestion I have is to *ditch the shell script entirely* and write the CLI in JavaScript.  You won't have to worry about this stuff.

I can send a PR if you wish.

**Comment by boneskull** [comment]
Another solution might be to install the [realpath](https://www.npmjs.com/package/realpath) module, but it'd have to be a peer dependency--and that will break under npm v3.

**Comment by Tjatse** [comment]
Yah, that's a bug. please try the alternative:
```
$ git clone https://github.com/Tjatse/pm2-gui.git
$ cd pm2-gui
$ npm install --production
# run monitor
$ ./pm2-gui <cmd> [options]
```

**Comment by Tjatse** [comment]
This should be fixed in `v0.1.4-alpha`
Try to test it via:
```
# npm install pm2-gui@0.1.4-alpha -g --production
# pm2-gui
# pm2-gui start /path/to/pm2-gui.ini
```

Feel free to open this or file a new one if this issue is still existing :)

**Comment by makkpsss** [comment]
Tried it on windows 10, not working! @Tjatse 
![capture](https://user-images.githubusercontent.com/32481718/37076396-678d6d2c-21fc-11e8-9cf6-cc2bf88c9cbe.PNG)

**Comment by droidMakk** [comment]
It's not working. tried it on windows!
![capture](https://user-images.githubusercontent.com/20293708/37076421-8644b55e-21fc-11e8-9895-7b8b0a6ea6d1.PNG)

**Comment by Tjatse** [comment]
pm2 based on axon's unix socket, i.e.: unix://some/path/conn.sock, this is not very friendly towards Windows, ;)

try `npm i pm2-gui -g` on unix and every thing will be okay
