### ISSUE TITLE
Decentralization

### ISSUE THREAD

**Issue by roccomuso** [Tjatse/pm2-gui#31]
Can the web interface be decentralized? Running on a remote server and receiving data from the pm2 instance?

**Comment by Tjatse** [comment]
Actually PM2 did not support remoting connection since v0.11.

**Comment by roccomuso** [comment]
I mean, can be possible to implement a dashboard like Keymetrics does?

**Comment by Tjatse** [comment]
![IMAGE](https://raw.githubusercontent.com/Tjatse/pm2-gui/master/screenshots/design.jpg)

## How to remote

1 Deploy `pm2-gui` on the `PM2` servers
  
  ```
  $ git clone https://github.com/Tjatse/pm2-gui.git
  $ cd pm2-gui
  $ npm install --production
  # run monitor
  ```

2 Update the `pm2-gui.ini` to run it as [an agent](https://github.com/Tjatse/pm2-gui#configuration)

3 Start the agent

  ```
  $ ./pm2-gui agent
  ```

4 Deploy `pm2-gui` on the server which you like

5 Update the `pm2-gui.ini` to run it as [an portal](https://github.com/Tjatse/pm2-gui#configuration)

6 Start the portal

  ```
  $ ./pm2-gui start
  ```

7 Open browser and try it:
 ![IMAGE](https://raw.githubusercontent.com/Tjatse/pm2-gui/master/screenshots/home.jpg)

**Comment by Tjatse** [comment]
Run `./pm2-gui` to get help.

**Comment by Tjatse** [comment]
@roccomuso Sorry, dude, I've never used Keymetrics's dashboard.
