### ISSUE TITLE
Host it on other than root (/) location

### ISSUE THREAD

**Issue by ageorgios** [Tjatse/pm2-gui#34]
Hello,
AMAZING work my friend thank you!

I am not able to make it work on a website like this:
example.com/pm2gui
using remote proxy on apache2

It only works when you access it from root location:
example.com/

it does not take into account if a proxy is used, here is a solution to honor proxies:
http://stackoverflow.com/questions/21856426/node-express-res-redirect-broken-when-using-proxy

**Comment by Zachary-Murphy** [comment]
I know this post was two years ago, but how did you get it too work with your website like example.com. I want to know you got it work. Because I have not been able to get it too work with a website domain.
