### ISSUE TITLE
 Authentication

### ISSUE THREAD

**Issue by angrypie** [Tjatse/pm2-gui#37]
I can't find any information about a password that i should provide when trying to login. Could anyone help me with this?

**Comment by ageorgios** [comment]
AuTh

**Comment by angrypie** [comment]
Oh... Only now i figured out that "AuTh" is actually password and not authentication type or something else. Thanks)

**Comment by SiriusED** [comment]
Jesus, I just figured out eiter that `authorization = AuTh` is the code for log in :)
