### ISSUE TITLE
can't get remote data

### ISSUE THREAD

**Issue by benishak** [Tjatse/pm2-gui#41]
I install pm2-gui on a remote server and add the configuration as follow in pm2-gui.ini

`pm2@server1 = password@http://pm2.myhost.com/sockserv`

well I can already access `http://pm2.myhost.com` and I don't get any error from the master pm2-gui

i'm running nginx

**Comment by Tjatse** [comment]
Please reference to [Serving apps locally with nginx and custom domain](https://github.com/Tjatse/pm2-gui#serv)
