### ISSUE TITLE
Agent cannot connect to web server (only the other way around)

### ISSUE THREAD

**Issue by iyinoluwaayoola** [Tjatse/pm2-gui#45]
@Tjatse, First of all, thanks for the great work!!!

For my use case, I have mobile applications (that is, I do not know their IPs, or they are behind a firewall and therefore cannot be reached) running on multiple raspberry pis and I like to monitor these PM2 processes without knowing the IPs. 

1. Is it possible that the pm2-gui agents running on the pis are configured to connect to a centralized web-server where they can all be monitored from? 
2. Is it possible to configure a bucket/namespace on the web-server to connect the agents to? This means i can view all the PM2 processes running on multiple hosts on a single web-interface.

THANKS AGAIN.

**Comment by Tjatse** [comment]
Please make sure your socket.io server (aka. pm2-gui agent) is online (reachable)!

**Comment by Tjatse** [comment]
1. in my case, my pm2 containers are running in a LAN, and the `pm2-gui`s are being deployed on a proxy/jump server, it access the `pm2-agents` via LAN, and Manager access the `pm2-gui` via Intranet.
2. COULD BE!! and what you purpose (need more info)?
