### ISSUE TITLE
Some strange text is mixed into the last picture of README 

### ISSUE THREAD

**Issue by yeze322** [Tjatse/pm2-gui#46]
Your README is really disharmony   (╯‵□′)╯︵┻━┻
Some strange text appeared in it!
I'm afraid your project may be harmonized by 110 in the future, I don't want to see that happen.

![alt text](https://github.com/Tjatse/pm2-gui/raw/master/screenshots/logs.jpg)

~~~But I like it~~~  (๑•̀ㅂ•́)و✧
~~~I guess you did it on purpose~~~

**Comment by Tjatse** [comment]
gotcha! ;)
