### ISSUE TITLE
[BUG] Conf.js not found

### ISSUE THREAD

**Issue by kevincaradant** [Tjatse/pm2-gui#47]
Hi

I installed pm2 with `npm install -g pm2` and then `npm install -g pm2-gui` and `pm2-gui start` but I get an error of file not found. 
```
[WARN] Can not load PM2 config, the file "/root/.pm2/conf.js" does not exist or empty, fallback to auto-load by pm2 home. 
[INFO] Spawning daemon...
[WARN] ✘ stopped
 [WARN] Can not load PM2 config, the file "/root/.pm2/conf.js" does not exist or empty, fallback to auto-load by pm2 home. 
[INFO] Daemonized with pid [3320].
[INFO] Forking slave...
[INFO] Ready!!!
[ERROR] (node:4123) DeprecationWarning: Calling an asynchronous function without callback is deprecated.
[INFO] Forking slave...
[ERROR] (node:4123) DeprecationWarning: Calling an asynchronous function without callback is deprecated.
[INFO] Forking slave...
[ERROR] (node:4123) DeprecationWarning: Calling an asynchronous function without callback is deprecated.
[INFO] Forking slave...
[ERROR] (node:4123) DeprecationWarning: Calling an asynchronous function without callback is deprecated.
[INFO] Forking slave...
[ERROR] (node:4123) DeprecationWarning: Calling an asynchronous function without callback is deprecated.
[INFO] Forking slave...
[ERROR] (node:4123) DeprecationWarning: Calling an asynchronous function without callback is deprecated.
[INFO] Forking slave...
[ERROR] (node:4123) DeprecationWarning: Calling an asynchronous function without callback is deprecated.
[INFO] Forking slave...
[ERROR] (node:4123) DeprecationWarning: Calling an asynchronous function without callback is deprecated.
[INFO] Forking slave...
[ERROR] (node:4123) DeprecationWarning: Calling an asynchronous function without callback is deprecated.



```

I tried npm install -g pm2-gui and also directly to compile from your sources as you recommend this way but I get a problem of conf.js not found... When I create the conf.js empty, the GUI of PM2-gui available in `http://localhoft:8088` is so ugly, no css , just a field authorization which didn't work. So I guess, I need of this file ?

![image](https://cloud.githubusercontent.com/assets/6093175/23877647/9551ce52-0843-11e7-9e6b-ae0d0fa65e32.png)

 How can I do that ? 

Is it a skeleton available of this file ? Other way ? 

Thank you in advance

Maybe can you suggest me the process to follow line by line but it's not the first time I use this project, I don't understand ;)

**Comment by Tjatse** [comment]
NEED MORE INFOS:
- 1. Whats your node version?
- 2. And `pm2` version?
- 3. Did you run `pm2` / `pm2-gui` by the same user?

**Comment by Tjatse** [comment]
It seems a breaking change on node v7.x:
[https://github.com/Tjatse/pm2-gui/blob/v0.1.4/lib/daemon.js#L121](https://github.com/Tjatse/pm2-gui/blob/v0.1.4/lib/daemon.js#L121)

I am working on the master for [v2](https://github.com/Tjatse/pm2-gui/issues/43), so, could you manually change your local code like following:
```
// lib/daemon.js#L121
fs.writeFileSync(pidfile, worker.pid)
// or 
// fs.writeFile(pidfile, worker.pid, function() {})
```

Please using `npm config get root` to locale the global `pm2-gui`.

**Comment by kevincaradant** [comment]
Yes sorry I forgot to mention these informations.
Node V7.7.2
PM2 V2.4.0
PM2-GUI: How to know the version ? I just did: `npm install -g pm2-gui`

npm config get root => answer:  undefined

Then, I changed / added the line mentioned in the daemon.js file in the local repository. Then I did `npm install -g` inside it. 
 don't see any difference. Ah yes just I don't have anymore the callback error :/
But always a bad GUI.
![image](https://cloud.githubusercontent.com/assets/6093175/23880273/f15f8b26-0852-11e7-90d6-24987a4e6f9b.png)


And stil this error:
```
[WARN] Can not load PM2 config, the file "/root/.pm2/conf.js" does not exist or empty, fallback to auto-load by pm2 home. 
[INFO] Spawning daemon...
[WARN] ✘ stopped
root@odroid:/home/odroid/pm2-gui# [WARN] Can not load PM2 config, the file "/root/.pm2/conf.js" does not exist or empty, fallback to auto-load by pm2 home. 
[INFO] Daemonized with pid [3864].
[INFO] Forking slave...
[INFO] Ready!!!
^C
root@odroid:/home/odroid/pm2-gui# pm2-gui start
[INFO] ✔ running



```

**Comment by Tjatse** [comment]
Gotcha!

Like what I mentioned above, the `origin master` is still under a heavy development, so, could you please download the [stable v0.1.4 source code](https://github.com/Tjatse/pm2-gui/archive/v0.1.4.zip) and do the jobs what you've done:
- `wget https://github.com/Tjatse/pm2-gui/archive/v0.1.4.zip`
- `unzip pm2-gui-0.1.4.zip`
- `cd pm2-gui-0.1.4`
- edit `daemon.js`
- `npm i`
- `bin/pm2-gui start`

**Comment by kevincaradant** [comment]
Just a little detail. It's unzip v.01.4 :)
How can I activate on start pm2-gui ? 

Then, big thank you, it's good now :)

But, really, I recommand you to always let the master stable. Normally, you have to develop on the dev branch and at the end, you merge or rebase your work on master but since two days I didn't understand why all was broken on your repo. The last version of npm is also broken, and normally, you don't build a broken version. It's just an advice :).

I get always the problem of conf.js but it's seems to work without this file finally :)

**Comment by Tjatse** [comment]
Indeed, I deleted the `next` branch accidentally, and pushed commits to `origin master` T.T

**Comment by kevincaradant** [comment]
No problem :) 

And about to run pm2-gui as service ? Is it possible today ? :)

**Comment by Tjatse** [comment]
Touch a `pm2-gui.ini` file and set `daemonize = true`.

ref: [https://github.com/Tjatse/pm2-gui/blob/master/pm2-gui.ini](https://github.com/Tjatse/pm2-gui/blob/master/pm2-gui.ini)

**Comment by kevincaradant** [comment]
Already done. I forgot to say you, that why I'm surprsing that didn't work

**Comment by kevincaradant** [comment]
Do you want I open a new issue for that and I remove my issue about service from here ?
