### ISSUE TITLE
[BUG] PM2-GUI service didn't work at the boot

### ISSUE THREAD

**Issue by kevincaradant** [Tjatse/pm2-gui#50]
Hi

I noticed on the V0.1.4, that when I write `daemonize = true` in `pm2-gui.ini` file but pm2-gui didn't start from itself.

I tried in command line: 
`service pm2-gui start`

I get that:
```
pm2-gui.service
   Loaded: not-found (Reason: No such file or directory)
   Active: inactive (dead)
```

Any workaround available ? Maybe I have to try some other old version ? 

I will let you to tell me what do you think.

Thank you in advance

Regards

PM2 Version: V2.4.0
PM2-GUI: V0.1.4

**Comment by Tjatse** [comment]
`service pm2-gui start` can not work, there is an alternative cmd:`pm2-gui start /path/to/pm2-gui.ini`
