### ISSUE TITLE
Remote monitoring

### ISSUE THREAD

**Issue by Droppers** [Tjatse/pm2-gui#55]
Hello,

How does the interface connect to the agent?

I have everything configured and added the agent to the [remotes] section in the pm2-gui.ini.

But it simply does not connect to the agent.. 

![screen](http://i.imgur.com/KYZUupM.png)

I am cleary doing something wrong, but I just can't figured it out.

Thank you.

**Comment by Tjatse** [comment]
can you just paste your `pm2-gui.ini` here (you can mask the remote ips)
