### ISSUE TITLE
Does pm2-gui support arm-architecture.

### ISSUE THREAD

**Issue by armenthiz** [Tjatse/pm2-gui#57]
I was install pm2-gui on beaglebone black. also pm2 was installed.
However when i start an application on pm2 and it started. and start pm2-gui, its not displaying any process in pm2-gui web.

Any solution for this? thanks

**Comment by armenthiz** [comment]
Sorry, it was my fault.

Im starting pm2-gui with _sudo_ command before, and realized that my application is running without _sudo_ command on pm2.

**Comment by Tjatse** [comment]
Yap, you should run pm2 and pm2-gui with the same user.
So, whats going on?

**Comment by armenthiz** [comment]
this solved thanks @Tjatse, i'll close this..
