### ISSUE TITLE
请问在npm上安装了最新版，如何在服务器上后台运行？

### ISSUE THREAD

**Issue by cheny95** [Tjatse/pm2-gui#58]
RT，不胜感激
不知道是否提供了方法或者依赖其他服务？
目前用nohup也实现了，总感觉不太好。

**Comment by Tjatse** [comment]
将你的`pm2-gui.ini` [L17](https://github.com/Tjatse/pm2-gui/blob/master/pm2-gui.ini#L17)改成
```
daemonize = true
```

然后terminal执行`pm2-gui start`

[参阅](https://github.com/Tjatse/pm2-gui#config)

**Comment by cheny95** [comment]
感谢，已经处理成功。
谢谢您提供了此插件。
