### ISSUE TITLE
can't see my localhost processes on the dashboard

### ISSUE THREAD

**Issue by wrfighting** [Tjatse/pm2-gui#59]
Hi, I clone the project, and run the script `node pm2-gui.js`, but I can't see my localhost processes on the dashboard.
I sure my node project is run by pm2.
I try to `npm install -g pm2-gui`, and run `pm2-gui start`, it works, I can see my localhost processes on the dashboard. But it's not my purpose.
I really need to run the script `node pm2-gui.js` to see my localhost processes, but it does not work can you help me?

**Comment by einsqing** [comment]
Me too.Did you solve it?

**Comment by einsqing** [comment]
Gotcha!

Like what I mentioned above, the origin master is still under a heavy development, so, could you please download the stable v0.1.4 source code and do the jobs what you've done:

wget https://github.com/Tjatse/pm2-gui/archive/v0.1.4.zip
unzip pm2-gui-0.1.4.zip
cd pm2-gui-0.1.4
edit daemon.js
npm i
bin/pm2-gui start
