### ISSUE TITLE
PM2-gui in remote server

### ISSUE THREAD

**Issue by checor** [Tjatse/pm2-gui#61]
Hello, I'm trying your software and its a very nice open source alternative.

I have tested it in a VPS, and I have it running wihtout problem. However, I want to know if there is a way PM2-gui is running a machine, and monitoring another machine(s).

Is there a way this can be done with this software? I suspect the remotes section is for that, but I don't have clue on how to use it.

Thanks!

**Comment by Tjatse** [comment]
it's definitely YES
1. run `pm2-gui agent` on your agent machines
2. serve a `pm2-gui` portal on your web machine by `pm2-gui start`
3. **make sure the connections of agents can be resolved everywhere (<ws|http>://<ip>:<port>)**
4. just visit `<your web ip address>:<port>`...
