### ISSUE TITLE
Conf.js not found

### ISSUE THREAD

**Issue by maxime-helen-sb** [Tjatse/pm2-gui#64]
```Error: Can not load PM2 config, the file ".pm2\conf.js" does not exist or empty```. The path is correct though. I am using pm2 v2.9.1.

I can't test your gui because of this error. I also tried with stable v0.1.4 source code.

I am looking forward to check your ui out! Thanks

**Comment by Tjatse** [comment]
Windows or Linux?

**Comment by maxime-helen-sb** [comment]
Windows

**Comment by DmitriyBerezin** [comment]
I also have warnings with the similar message on start command on Mac. Here is an output:

```
[INFO] Starting...
[WARN] Can not load PM2 config, the file "/Users/yoyoseek/.pm2/conf.js" does not exist or empty, fallback to auto-load by pm2 home. 
[WARN] Can not load PM2 config, the file "/Users/yoyoseek/.pm2/conf.js" does not exist or empty, fallback to auto-load by pm2 home. 
[ERROR] (node:41627) [DEP0013] DeprecationWarning: Calling an asynchronous function without callback is deprecated.
[INFO] ✔ running
```

Does this output means success or it is not ok? Thank you

**Comment by Tjatse** [comment]
it's fine
