### ISSUE TITLE
How to host it on a domain from freenom when I have IP Address with Port?

### ISSUE THREAD

**Issue by Zachary-Murphy** [Tjatse/pm2-gui#65]
How, do I host my web viewer to my domain from freenom when I have an IP Address with Port? How do I set it up with DNS? I am using a Raspberry Pi 3 with Pm2 and Pm2-gui on it.

I want to do this so that I can view my pm2 instances from School, or anywhere. 

Can someone please help me setup Pm2-gui so that I can view it on my site. My site is frappejs.ga

**Comment by Tjatse** [comment]
Maybe the [Serving apps locally with nginx and custom domain](https://github.com/Tjatse/pm2-gui#serv) section could help you.
