### ISSUE TITLE
Can not run the module

### ISSUE THREAD

**Issue by SiriusED** [Tjatse/pm2-gui#68]
OS - Windows 10 - Pro.
Node v6.10.3
PM2 2.10.1
PM2-GUI: V0.1.4

----
That what I got after start:
```
$ pm2-gui start
[INFO] Starting...
/c/Users/developer/AppData/Roaming/npm/node_modules/pm2-gui/pm2-gui: line 49: /c/Program: No such file or directory
[WARN] ✘ stopped
```

What is wrong and how to fix it?

**Comment by SiriusED** [comment]
Fixed it by set right path for node. But still cant run here is an error:
```
[INFO] Starting...
[WARN] Can not load PM2 config, the file "C:\Users\developer\.pm2\conf.js" does not exist or empty, fallback to auto-load by pm2 home.
C:\Users\developer\AppData\Roaming\npm\node_modules\pm2-gui\lib\monitor.js:156
      throw new Error(fbMsg + 'Unfortunately ' + (val || prop) + ' can not found, please makesure that your pm2 is running and the home path is correct.')
      ^

```

**Comment by SiriusED** [comment]
Ya, I installed ubuntu and It launched by first try... But where can I find the password for auth page?

**Comment by ohoroyoi** [comment]
@Tjatse I added conf.js. it was not empty and exists also. but still error messages returns. Why do you think this is happening?
