### ISSUE TITLE
I'm getting strange bugs with custom config

### ISSUE THREAD

**Issue by zxqfox** [Tjatse/pm2-gui#7]
If I starting app with custom config each time I see "Invalid namespace" in the answer.

Also I can't update local pm2-gui.json (it loads it but writes to ~/.pm2/pm2-gui.json).

Bug repeated with both: 0.10@latest and iojs-1.0.4
Also I'm using installed pm2-gui to node_modules and running ./node_modules/.bin/pm2-gui start --config ./pm2-gui.json (Actually a copy of .file in /.pm2/: `cp ~/.pm2/pm2-gui.json ./`).

What does that mean? How to fix that?

**Comment by Tjatse** [comment]
So, are you playing with io.js? I've never tested on that, it's for node.js.

**Comment by zxqfox** [comment]
@Tjatse It's working fine. Troubles only when I specify custom configuration ;-)
