### ISSUE TITLE
Web doesn't show any process

### ISSUE THREAD

**Issue by jenguidanos** [Tjatse/pm2-gui#71]
I know there are other issues with the same question but they don't solve my problem.

* Using pm2 2.10.4 and pm2-gui 0.1.4 (as seen on /usr/local/lib/node_modules/pm2-gui)
* Both installed with `npm i -g`
* To start pm2-gui: `pm2-gui start ~/pm2-gui/pm2-gui.ini` (i have an old copy of the master branch in my home dir, but i think global command `pm2-gui` runs from /usr/local/lib/node_modules)
* `pm2-gui mon` works well and i can see my processes
* On the web, the processes sections show a blank page and the webdev console doesn't show any error, on the remote tab i can see some request to the socket.io server, all with 200 or 101 status.
* I've tried both IP and nginx subdomain to access the web page

Output when i run `pm2-gui start ~/pm2-gui/pm2-gui.ini`
```
[INFO] Starting...
[WARN] Can not load PM2 config, the file "/home/m2m/.pm2/conf.js" does not exist or empty, fallback to auto-load by pm2 home.
[INFO] Spawning daemon...
[WARN] Can not load PM2 config, the file "/home/m2m/.pm2/conf.js" does not exist or empty, fallback to auto-load by pm2 home.
[INFO] Daemonized with pid [18844].
[INFO] Forking slave...
[INFO] Ready!!!
[INFO] ✔ running
```

After `start` command if i do a `restart`:
```
[INFO] Restarting...
[WARN] A slave-worker is running...
[WARN] ✘ stopped
```

My pm2-gui.ini:
```pm2 = ~/.pm2
refresh = 5s
port = 8088
daemonize = true
readonly = true
process_refresh = 3s
[log]
dir = ./logs
prefix = true
date = false
level = info
[agent]
authorization = Sup3rCal1Frag1l
[remotes]
```

`pm2-gui logs`:
```
[INFO] Logs from /usr/local/lib/node_modules/pm2-gui/logs/pm2-gui.out and /usr/local/lib/node_modules/pm2-gui/logs/pm2-gui.err:
==> /usr/local/lib/node_modules/pm2-gui/logs/pm2-gui.out <==
[INFO] Listening connection event on sys by func:_connectSysSocket
[INFO] Listening connection event on log by func:_connectLogSocket
[INFO] Listening connection event on process by func:_connectProcessSocket
[INFO] Connecting to pm2 daemon: /home/m2m/.pm2/pub.sock
[INFO] [pm2:log] Activate
[INFO] Web server is listening on 127.0.0.1:8088
[INFO] awake:1st api-0
[INFO] [pm2:log] deactivate 'cause no subscriber
[INFO] Connected to /system!
[INFO] Fetching pm2 version: /home/m2m/.pm2/rpc.sock
[INFO] Shutting down....
[INFO] Completed!

==> /usr/local/lib/node_modules/pm2-gui/logs/pm2-gui.err <==
[WARN] Can not load PM2 config, the file "/home/m2m/.pm2/conf.js" does not exist or empty, fallback to auto-load by pm2 home.
[WARN] Avoid duplicated listening!
```

**Comment by Tjatse** [comment]
Just visit pm2-gui web in Google Chrome browser and open the Develop Tools (alt+option+i) -> Console, can you get some console errors?

**Comment by jenguidanos** [comment]
Sorry @Tjatse , no, no output in the chrome's console, also network panel (xhr tab) only shows request (GET/POST) with 200 status code

**Comment by RedSparr0w** [comment]
I'm having the same problem, No processes are shown, No console errors at all.

**Comment by macctown** [comment]
Same issue here, do you resolve this issue?

**Comment by kaushikmahato** [comment]
I see a lot of people facing this issue but no fix, recently I observed it was working sometimes and not sometimes as I was trying to run it in WSL Ubuntu. I believe there is some issue with the configuration but wasn't able to conclude on it as there was no in depth logging and documentation. I wish to identify this issue and maybe solve this but not able to.

@Tjatse  will need your help

I was using node 12.16.2
with pm2 4.2.3 (also tried 4.4.0)

**Comment by Fransferdy** [comment]
I thank you oh might heresergio, after a day struggling to get this to work, it was your patch that was the solution! Thank you so much!

**Comment by Tjatse** [comment]
Ref #84
