### ISSUE TITLE
error installing on ubuntu (contabo vps)

### ISSUE THREAD

**Issue by Ivanverdonck** [Tjatse/pm2-gui#72]
Hello,

I get following error on an Cobtabo VPS: EBADPLATFORM

Additional info: Ubuntu 16.4 (uname result: 4.4.0-127-generic x86_64 x86_64 x86_64 GNU/Linux)

Thanks,
Ivan.

_619 verbose stack Error: Unsupported
619 verbose stack     at checkPlatform (/usr/share/npm/node_modules/npm-install-checks/index.js:46:14)
619 verbose stack     at Array.<anonymous> (/usr/share/npm/node_modules/slide/lib/bind-actor.js:15:8)
619 verbose stack     at LOOP (/usr/share/npm/node_modules/slide/lib/chain.js:15:14)
619 verbose stack     at /usr/share/npm/node_modules/slide/lib/chain.js:18:7
619 verbose stack     at checkEngine (/usr/share/npm/node_modules/npm-install-checks/index.js:10:20)
619 verbose stack     at Array.<anonymous> (/usr/share/npm/node_modules/slide/lib/bind-actor.js:15:8)
619 verbose stack     at LOOP (/usr/share/npm/node_modules/slide/lib/chain.js:15:14)
619 verbose stack     at chain (/usr/share/npm/node_modules/slide/lib/chain.js:20:5)
619 verbose stack     at module.exports.isInstallable (/usr/share/npm/lib/install/validate-args.js:26:3)
619 verbose stack     at resolveWithNewModule (/usr/share/npm/lib/install/deps.js:463:12)
620 verbose pkgid windows-cpu@0.1.5
621 verbose cwd /root
622 error Linux 4.4.0-127-generic
623 error argv "/usr/bin/nodejs" "/usr/bin/npm" "install" "pm2-gui" "-g"
624 error node v4.2.6
625 error npm  v3.5.2
626 error code EBADPLATFORM
627 error notsup Not compatible with your operating system or architecture: windows-cpu@0.1.5
628 error notsup Valid OS:    !darwin,!linux,win32
628 error notsup Valid Arch:  any
628 error notsup Actual OS:   linux
628 error notsup Actual Arch: x64
629 verbose exit [ 1, true ]_

**Comment by KyleRoss** [comment]
I'm the owner of `windows-cpu` which was affecting your install. I've made a change that should prevent this issue from happening. Can you try again?

**Comment by Tjatse** [comment]
@KyleRoss 👍
